[package]
name    = "keyless_nginx"
version = "0.0.1"
authors = ["Tom Thorogood <me@tomthorogood.co.uk>"]
publish = false

[lib]
name       = "keyless_nginx"
crate-type = ["staticlib"]

[dependencies]
libc           = "0.2"
num            = "0.1"
enum_primitive = "0.1"